ERR : test: Success
ERR : again: Success
OUT : test
OUT : test 2
OUT : again
ERR : test: Success
a.out: t.cpp:15: int main(): Assertion `1 + 1 == 5' failed.
ERR : test: Success
a.out: t.cpp:19: int main(): Assertion `1 + 1 == 5' failed.
ERR : test: Success
a.out: t.cpp:19: int main(): Assertion `1 + 1 == 5' failed.
ERR : test: Success
OUT : test
OUT : test 2
AAAAAA
a.out: t.cpp:19: int main(): Assertion `1 + 1 == 5' failed.
